module StackChan
  class Controller
    class Error < StandardError
    end

    class TimeoutError < Error
    end

    class DeviceError < Error
    end

    class ConnectionError < Error
    end

    class Busy < ConnectionError
    end

    class LinkChanged < Error
    end
  end
end
