class Si12T
  interface _Bus
    def write: (Integer i2c_adrs_7, *(Integer | String | Array[Integer]) outputs) -> Integer
    def read: (Integer i2c_adrs_7, Integer len, *(Integer | String | Array[Integer]) outputs) -> String
  end

  ADDR: Integer
  REG_CTRL1: Integer
  REG_CTRL2: Integer
  REG_OUTPUT1: Integer
  ENABLE_REGS: Range[Integer]
  SENS_REGS: Range[Integer]
  ZONE_COUNT: Integer

  @i2c: _Bus
  @prev_touched: bool

  def initialize: (_Bus i2c) -> void
  def init_sensor: () -> void
  def read_zones: () -> Array[Integer]
  def poll: () -> Integer?
end
