source "https://rubygems.org"

gem "rb-foundation-model-mac", git: "https://github.com/bash0C7/rb-foundation-model-mac.git", branch: "main"
gem "drb"
gem "logger"

group :test do
  gem "test-unit"
  gem "rake"
end
