#!/usr/bin/env ruby
# aot/kernels/*.rb -> one suppify gem (picoruby-stackchan_aot) plus
# picoruby-kernel_registry, the multicore_kernels table picoruby-multicore
# looks kernels up in. All files are merged into one library so the firmware
# carries one spinel runtime (two suppify gems in one image also collide at
# link time).
#
#   tools/aot/kernels_build.rb <esp32|host>
#
# Output under build/aot/<board>/. The last stdout line is the ":"-separated
# gem dirs for STACKCHAN_AOT_GEMS. Needs tools/aot/setup.sh first.
require "digest"
require "fileutils"

ROOT  = File.expand_path("../..", __dir__)
LIB   = "stackchan_aot"
KDIR  = File.join(ROOT, "aot", "kernels")
AOT   = File.join(ROOT, "build", "aot")

def die(msg)
  warn "kernels_build: #{msg}"
  exit 2
end

board = ARGV[0]
die "usage: tools/aot/kernels_build.rb <esp32|host>" unless %w[esp32 host].include?(board)
suppify = File.join(AOT, "suppify", "suppify.rb")
spinel  = File.join(AOT, "spinel", "bin", "spinel")
die "run tools/aot/setup.sh first" unless File.exist?(suppify) && File.executable?(spinel)

sources = Dir[File.join(KDIR, "*.rb")].sort
die "no kernels in #{KDIR}" if sources.empty?
merged = sources.map { |f| "# ---- #{File.basename(f)} ----\n" + File.read(f) }.join("\n")

out = File.join(AOT, board)
gems_dir = File.join(out, "gems")
gem = File.join(gems_dir, "picoruby-#{LIB}")
stamp = File.join(gems_dir, "#{LIB}.stamp")
FileUtils.mkdir_p(gems_dir)
merged_rb = File.join(out, "#{LIB}.rb")
File.write(merged_rb, merged)

shim = Dir[File.join(ROOT, "aot", "mcu-shim", "**", "*")].sort.select { |f| File.file?(f) }
inputs = [merged, board, File.read(File.join(ROOT, "aot", "suppify.pin")),
          File.read(File.join(ROOT, "tools", "aot", "prepare_mcu.sh")), *shim.map { |f| File.read(f) }]
want = Digest::SHA256.hexdigest(inputs.join("\0"))
unless File.directory?(gem) && File.exist?(stamp) && File.read(stamp).strip == want
  FileUtils.rm_rf(gem)
  env = { "SPINEL" => spinel, "SPINEL_LIB" => File.join(AOT, "spinel", "lib") }
  ok = system(env, "ruby", "-I", File.join(AOT, "suppify", "lib"), suppify, merged_rb,
              "-o", LIB, "-t", "picoruby", "-d", gems_dir, out: $stderr, chdir: out)
  die "suppify failed" unless ok
  if board == "esp32"
    ok = system(File.join(ROOT, "tools", "aot", "prepare_mcu.sh"), gem, "esp32", out: $stderr)
    die "prepare_mcu failed" unless ok
  end
  File.write(stamp, "#{want}\n")
end

header = File.read(File.join(gem, "include", "#{LIB}.h"))
entries = header.scan(/^int32_t #{LIB}_(\w+)_call\(/).flatten

reg = File.join(out, "picoruby-kernel_registry")
FileUtils.rm_rf(reg)
FileUtils.mkdir_p(File.join(reg, "src"))
FileUtils.mkdir_p(File.join(reg, "mrblib"))
File.write(File.join(reg, "mrblib", "kernel_registry.rb"), <<~RUBY)
  # The C table in src/kernel_registry.c is what picoruby-multicore reads; this
  # file only anchors the gem. Generated by tools/aot/kernels_build.rb.
RUBY
File.write(File.join(reg, "mrbgem.rake"), <<~RAKE)
  MRuby::Gem::Specification.new('picoruby-kernel_registry') do |spec|
    spec.license = 'MIT'
    spec.author  = 'bash0C7'
    spec.summary = 'name -> C entry table of the AOT kernels (generated)'
    spec.cc.include_paths << "\#{dir}/../gems/picoruby-#{LIB}/include"
  end
RAKE
File.write(File.join(reg, "src", "kernel_registry.c"), <<~C)
  /* Generated by tools/aot/kernels_build.rb. Do not edit. */
  #include <stddef.h>
  #include <stdint.h>
  #include <stdio.h>
  #include "#{LIB}.h"

  static char error_buf[256];
  static const char *error_text(void) {
    const char *cls = #{LIB}_error_class();
    const char *msg = #{LIB}_error_message();
    if (!msg) msg = "";
    if (cls && cls[0]) snprintf(error_buf, sizeof error_buf, "%s: %s", cls, msg);
    else snprintf(error_buf, sizeof error_buf, "%s", msg);
    return error_buf;
  }

  typedef int32_t (*multicore_kernel_fn)(const uint8_t *in, int32_t in_len, uint8_t *out, int32_t out_cap);
  typedef struct {
    const char *name;
    multicore_kernel_fn call;
    const char *(*signature)(void);
    void (*init)(void);
    const char *(*error_message)(void);
  } multicore_kernel_t;

  const multicore_kernel_t multicore_kernels[] = {
  #{entries.map { |m| "  { \"#{m}\", #{LIB}_#{m}_call, #{LIB}_#{m}_signature, #{LIB}_init, error_text }," }.join("\n")}
    { NULL, NULL, NULL, NULL, NULL }
  };

  void mrb_picoruby_kernel_registry_gem_init(void *mrb) { (void)mrb; }
  void mrb_picoruby_kernel_registry_gem_final(void *mrb) { (void)mrb; }
C

warn "kernels_build: #{entries.size} kernel(s) [#{board}]: #{entries.join(' ')}"
puts [gem, reg].join(":")
