/* Generated by Spinel (--ext-init stackchan_aot_spinel). The contract for a host
   shim: call stackchan_aot_spinel() once before any entry; wrap entry calls in
   stackchan_aot_spinel_try to receive a Ruby raise as (class name, message). */
#ifndef SPINEL_EXT_H
#define SPINEL_EXT_H
#define SPINEL_EXT_HOST 1  /* runtime globals resolve to the kernel TU */
#include "spinel_rt.h"

void stackchan_aot_spinel(void);
int stackchan_aot_spinel_try(void (*fn)(void *), void *ctx, const char **cls, const char **msg);

const char * sp_SuppiExport_stackchan_aot_s_suppi_ulaw_decode(const char * lv_p0);
const char * sp_SuppiExport_stackchan_aot_s_suppi_glyph_row(sp_int lv_p0, sp_int lv_p1, sp_int lv_p2, sp_int lv_p3);
const char * sp_SuppiExport_stackchan_aot_s_suppi_glyph16(sp_int lv_p0, sp_int lv_p1, sp_int lv_p2, sp_int lv_p3, sp_int lv_p4, sp_int lv_p5, sp_int lv_p6, sp_int lv_p7, sp_int lv_p8, sp_int lv_p9, sp_int lv_p10, sp_int lv_p11, sp_int lv_p12, sp_int lv_p13, sp_int lv_p14, sp_int lv_p15, sp_int lv_p16, sp_int lv_p17, sp_int lv_p18);

#endif
